name: projectapp_donation
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-282.1.beta

# Add regular dependencies here.
dependencies:
csv: ^6.0.0
ansicolor: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  csv: ^6.0.0
  lints: ^3.0.0
  test: ^1.24.0
